/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as ProtectedExampleProtectedRouteRouteImport } from './routes/_protected/example-protected-route'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ProtectedAdminSetupRouteImport } from './routes/_protected/admin-setup'
import { Route as ProtectedAdminRouteImport } from './routes/_protected/admin'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignOutRouteImport } from './routes/_auth/sign-out'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as ApiHelloRouteImport } from './routes/_api/hello'
import { Route as ProtectedDashboardIndexRouteImport } from './routes/_protected/dashboard/index'
import { Route as ProtectedAdminIndexRouteImport } from './routes/_protected/admin/index'
import { Route as ProtectedDashboardSupportRouteImport } from './routes/_protected/dashboard/support'
import { Route as ProtectedDashboardSharingRouteImport } from './routes/_protected/dashboard/sharing'
import { Route as ProtectedDashboardSettingsRouteImport } from './routes/_protected/dashboard/settings'
import { Route as ProtectedDashboardPracticeRouteImport } from './routes/_protected/dashboard/practice'
import { Route as ProtectedDashboardOsceRouteImport } from './routes/_protected/dashboard/osce'
import { Route as ProtectedDashboardNotificationsRouteImport } from './routes/_protected/dashboard/notifications'
import { Route as ProtectedDashboardNotesRouteImport } from './routes/_protected/dashboard/notes'
import { Route as ProtectedDashboardBookmarksRouteImport } from './routes/_protected/dashboard/bookmarks'
import { Route as ProtectedAdminUsersRouteImport } from './routes/_protected/admin/users'
import { Route as ProtectedAdminSupportRouteImport } from './routes/_protected/admin/support'
import { Route as ProtectedAdminQuestionsRouteImport } from './routes/_protected/admin/questions'
import { Route as ProtectedAdminPlansRouteImport } from './routes/_protected/admin/plans'
import { Route as ProtectedAdminOsceRouteImport } from './routes/_protected/admin/osce'
import { Route as ProtectedAdminNotificationsRouteImport } from './routes/_protected/admin/notifications'
import { Route as ProtectedAdminFeedbackRouteImport } from './routes/_protected/admin/feedback'
import { Route as ProtectedAdminCategoriesRouteImport } from './routes/_protected/admin/categories'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const ProtectedExampleProtectedRouteRoute =
  ProtectedExampleProtectedRouteRouteImport.update({
    id: '/example-protected-route',
    path: '/example-protected-route',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminSetupRoute = ProtectedAdminSetupRouteImport.update({
  id: '/admin-setup',
  path: '/admin-setup',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminRoute = ProtectedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => ProtectedRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignOutRoute = AuthSignOutRouteImport.update({
  id: '/sign-out',
  path: '/sign-out',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AuthRoute,
} as any)
const ApiHelloRoute = ApiHelloRouteImport.update({
  id: '/_api/hello',
  path: '/hello',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardIndexRoute = ProtectedDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedAdminIndexRoute = ProtectedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedDashboardSupportRoute =
  ProtectedDashboardSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSharingRoute =
  ProtectedDashboardSharingRouteImport.update({
    id: '/sharing',
    path: '/sharing',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardSettingsRoute =
  ProtectedDashboardSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardPracticeRoute =
  ProtectedDashboardPracticeRouteImport.update({
    id: '/practice',
    path: '/practice',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardOsceRoute = ProtectedDashboardOsceRouteImport.update({
  id: '/osce',
  path: '/osce',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardNotificationsRoute =
  ProtectedDashboardNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedDashboardNotesRoute = ProtectedDashboardNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => ProtectedDashboardRoute,
} as any)
const ProtectedDashboardBookmarksRoute =
  ProtectedDashboardBookmarksRouteImport.update({
    id: '/bookmarks',
    path: '/bookmarks',
    getParentRoute: () => ProtectedDashboardRoute,
  } as any)
const ProtectedAdminUsersRoute = ProtectedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminSupportRoute = ProtectedAdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminQuestionsRoute = ProtectedAdminQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminPlansRoute = ProtectedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminOsceRoute = ProtectedAdminOsceRouteImport.update({
  id: '/osce',
  path: '/osce',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminNotificationsRoute =
  ProtectedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)
const ProtectedAdminFeedbackRoute = ProtectedAdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ProtectedAdminRoute,
} as any)
const ProtectedAdminCategoriesRoute =
  ProtectedAdminCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => ProtectedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/hello': typeof ApiHelloRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin': typeof ProtectedAdminRouteWithChildren
  '/admin-setup': typeof ProtectedAdminSetupRoute
  '/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/': typeof PublicIndexRoute
  '/admin/categories': typeof ProtectedAdminCategoriesRoute
  '/admin/feedback': typeof ProtectedAdminFeedbackRoute
  '/admin/notifications': typeof ProtectedAdminNotificationsRoute
  '/admin/osce': typeof ProtectedAdminOsceRoute
  '/admin/plans': typeof ProtectedAdminPlansRoute
  '/admin/questions': typeof ProtectedAdminQuestionsRoute
  '/admin/support': typeof ProtectedAdminSupportRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/dashboard/bookmarks': typeof ProtectedDashboardBookmarksRoute
  '/dashboard/notes': typeof ProtectedDashboardNotesRoute
  '/dashboard/notifications': typeof ProtectedDashboardNotificationsRoute
  '/dashboard/osce': typeof ProtectedDashboardOsceRoute
  '/dashboard/practice': typeof ProtectedDashboardPracticeRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/sharing': typeof ProtectedDashboardSharingRoute
  '/dashboard/support': typeof ProtectedDashboardSupportRoute
  '/admin/': typeof ProtectedAdminIndexRoute
  '/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesByTo {
  '/hello': typeof ApiHelloRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-out': typeof AuthSignOutRoute
  '/sign-up': typeof AuthSignUpRoute
  '/admin-setup': typeof ProtectedAdminSetupRoute
  '/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/privacy': typeof PublicPrivacyRoute
  '/terms': typeof PublicTermsRoute
  '/': typeof PublicIndexRoute
  '/admin/categories': typeof ProtectedAdminCategoriesRoute
  '/admin/feedback': typeof ProtectedAdminFeedbackRoute
  '/admin/notifications': typeof ProtectedAdminNotificationsRoute
  '/admin/osce': typeof ProtectedAdminOsceRoute
  '/admin/plans': typeof ProtectedAdminPlansRoute
  '/admin/questions': typeof ProtectedAdminQuestionsRoute
  '/admin/support': typeof ProtectedAdminSupportRoute
  '/admin/users': typeof ProtectedAdminUsersRoute
  '/dashboard/bookmarks': typeof ProtectedDashboardBookmarksRoute
  '/dashboard/notes': typeof ProtectedDashboardNotesRoute
  '/dashboard/notifications': typeof ProtectedDashboardNotificationsRoute
  '/dashboard/osce': typeof ProtectedDashboardOsceRoute
  '/dashboard/practice': typeof ProtectedDashboardPracticeRoute
  '/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/dashboard/sharing': typeof ProtectedDashboardSharingRoute
  '/dashboard/support': typeof ProtectedDashboardSupportRoute
  '/admin': typeof ProtectedAdminIndexRoute
  '/dashboard': typeof ProtectedDashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_auth': typeof AuthRouteWithChildren
  '/_protected': typeof ProtectedRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_api/hello': typeof ApiHelloRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-out': typeof AuthSignOutRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_protected/admin': typeof ProtectedAdminRouteWithChildren
  '/_protected/admin-setup': typeof ProtectedAdminSetupRoute
  '/_protected/dashboard': typeof ProtectedDashboardRouteWithChildren
  '/_protected/example-protected-route': typeof ProtectedExampleProtectedRouteRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/': typeof PublicIndexRoute
  '/_protected/admin/categories': typeof ProtectedAdminCategoriesRoute
  '/_protected/admin/feedback': typeof ProtectedAdminFeedbackRoute
  '/_protected/admin/notifications': typeof ProtectedAdminNotificationsRoute
  '/_protected/admin/osce': typeof ProtectedAdminOsceRoute
  '/_protected/admin/plans': typeof ProtectedAdminPlansRoute
  '/_protected/admin/questions': typeof ProtectedAdminQuestionsRoute
  '/_protected/admin/support': typeof ProtectedAdminSupportRoute
  '/_protected/admin/users': typeof ProtectedAdminUsersRoute
  '/_protected/dashboard/bookmarks': typeof ProtectedDashboardBookmarksRoute
  '/_protected/dashboard/notes': typeof ProtectedDashboardNotesRoute
  '/_protected/dashboard/notifications': typeof ProtectedDashboardNotificationsRoute
  '/_protected/dashboard/osce': typeof ProtectedDashboardOsceRoute
  '/_protected/dashboard/practice': typeof ProtectedDashboardPracticeRoute
  '/_protected/dashboard/settings': typeof ProtectedDashboardSettingsRoute
  '/_protected/dashboard/sharing': typeof ProtectedDashboardSharingRoute
  '/_protected/dashboard/support': typeof ProtectedDashboardSupportRoute
  '/_protected/admin/': typeof ProtectedAdminIndexRoute
  '/_protected/dashboard/': typeof ProtectedDashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/hello'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/admin'
    | '/admin-setup'
    | '/dashboard'
    | '/example-protected-route'
    | '/privacy'
    | '/terms'
    | '/'
    | '/admin/categories'
    | '/admin/feedback'
    | '/admin/notifications'
    | '/admin/osce'
    | '/admin/plans'
    | '/admin/questions'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/bookmarks'
    | '/dashboard/notes'
    | '/dashboard/notifications'
    | '/dashboard/osce'
    | '/dashboard/practice'
    | '/dashboard/settings'
    | '/dashboard/sharing'
    | '/dashboard/support'
    | '/admin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/hello'
    | '/sign-in'
    | '/sign-out'
    | '/sign-up'
    | '/admin-setup'
    | '/example-protected-route'
    | '/privacy'
    | '/terms'
    | '/'
    | '/admin/categories'
    | '/admin/feedback'
    | '/admin/notifications'
    | '/admin/osce'
    | '/admin/plans'
    | '/admin/questions'
    | '/admin/support'
    | '/admin/users'
    | '/dashboard/bookmarks'
    | '/dashboard/notes'
    | '/dashboard/notifications'
    | '/dashboard/osce'
    | '/dashboard/practice'
    | '/dashboard/settings'
    | '/dashboard/sharing'
    | '/dashboard/support'
    | '/admin'
    | '/dashboard'
  id:
    | '__root__'
    | '/_auth'
    | '/_protected'
    | '/_public'
    | '/_api/hello'
    | '/_auth/sign-in'
    | '/_auth/sign-out'
    | '/_auth/sign-up'
    | '/_protected/admin'
    | '/_protected/admin-setup'
    | '/_protected/dashboard'
    | '/_protected/example-protected-route'
    | '/_public/privacy'
    | '/_public/terms'
    | '/_public/'
    | '/_protected/admin/categories'
    | '/_protected/admin/feedback'
    | '/_protected/admin/notifications'
    | '/_protected/admin/osce'
    | '/_protected/admin/plans'
    | '/_protected/admin/questions'
    | '/_protected/admin/support'
    | '/_protected/admin/users'
    | '/_protected/dashboard/bookmarks'
    | '/_protected/dashboard/notes'
    | '/_protected/dashboard/notifications'
    | '/_protected/dashboard/osce'
    | '/_protected/dashboard/practice'
    | '/_protected/dashboard/settings'
    | '/_protected/dashboard/sharing'
    | '/_protected/dashboard/support'
    | '/_protected/admin/'
    | '/_protected/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  ApiHelloRoute: typeof ApiHelloRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_protected/example-protected-route': {
      id: '/_protected/example-protected-route'
      path: '/example-protected-route'
      fullPath: '/example-protected-route'
      preLoaderRoute: typeof ProtectedExampleProtectedRouteRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin-setup': {
      id: '/_protected/admin-setup'
      path: '/admin-setup'
      fullPath: '/admin-setup'
      preLoaderRoute: typeof ProtectedAdminSetupRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin': {
      id: '/_protected/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof ProtectedAdminRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-out': {
      id: '/_auth/sign-out'
      path: '/sign-out'
      fullPath: '/sign-out'
      preLoaderRoute: typeof AuthSignOutRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_api/hello': {
      id: '/_api/hello'
      path: '/hello'
      fullPath: '/hello'
      preLoaderRoute: typeof ApiHelloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard/': {
      id: '/_protected/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof ProtectedDashboardIndexRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/admin/': {
      id: '/_protected/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof ProtectedAdminIndexRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/dashboard/support': {
      id: '/_protected/dashboard/support'
      path: '/support'
      fullPath: '/dashboard/support'
      preLoaderRoute: typeof ProtectedDashboardSupportRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/sharing': {
      id: '/_protected/dashboard/sharing'
      path: '/sharing'
      fullPath: '/dashboard/sharing'
      preLoaderRoute: typeof ProtectedDashboardSharingRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/settings': {
      id: '/_protected/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof ProtectedDashboardSettingsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/practice': {
      id: '/_protected/dashboard/practice'
      path: '/practice'
      fullPath: '/dashboard/practice'
      preLoaderRoute: typeof ProtectedDashboardPracticeRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/osce': {
      id: '/_protected/dashboard/osce'
      path: '/osce'
      fullPath: '/dashboard/osce'
      preLoaderRoute: typeof ProtectedDashboardOsceRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/notifications': {
      id: '/_protected/dashboard/notifications'
      path: '/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof ProtectedDashboardNotificationsRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/notes': {
      id: '/_protected/dashboard/notes'
      path: '/notes'
      fullPath: '/dashboard/notes'
      preLoaderRoute: typeof ProtectedDashboardNotesRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/dashboard/bookmarks': {
      id: '/_protected/dashboard/bookmarks'
      path: '/bookmarks'
      fullPath: '/dashboard/bookmarks'
      preLoaderRoute: typeof ProtectedDashboardBookmarksRouteImport
      parentRoute: typeof ProtectedDashboardRoute
    }
    '/_protected/admin/users': {
      id: '/_protected/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof ProtectedAdminUsersRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/support': {
      id: '/_protected/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof ProtectedAdminSupportRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/questions': {
      id: '/_protected/admin/questions'
      path: '/questions'
      fullPath: '/admin/questions'
      preLoaderRoute: typeof ProtectedAdminQuestionsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/plans': {
      id: '/_protected/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof ProtectedAdminPlansRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/osce': {
      id: '/_protected/admin/osce'
      path: '/osce'
      fullPath: '/admin/osce'
      preLoaderRoute: typeof ProtectedAdminOsceRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/notifications': {
      id: '/_protected/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof ProtectedAdminNotificationsRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/feedback': {
      id: '/_protected/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof ProtectedAdminFeedbackRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
    '/_protected/admin/categories': {
      id: '/_protected/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof ProtectedAdminCategoriesRouteImport
      parentRoute: typeof ProtectedAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignOutRoute: typeof AuthSignOutRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthSignInRoute: AuthSignInRoute,
  AuthSignOutRoute: AuthSignOutRoute,
  AuthSignUpRoute: AuthSignUpRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface ProtectedAdminRouteChildren {
  ProtectedAdminCategoriesRoute: typeof ProtectedAdminCategoriesRoute
  ProtectedAdminFeedbackRoute: typeof ProtectedAdminFeedbackRoute
  ProtectedAdminNotificationsRoute: typeof ProtectedAdminNotificationsRoute
  ProtectedAdminOsceRoute: typeof ProtectedAdminOsceRoute
  ProtectedAdminPlansRoute: typeof ProtectedAdminPlansRoute
  ProtectedAdminQuestionsRoute: typeof ProtectedAdminQuestionsRoute
  ProtectedAdminSupportRoute: typeof ProtectedAdminSupportRoute
  ProtectedAdminUsersRoute: typeof ProtectedAdminUsersRoute
  ProtectedAdminIndexRoute: typeof ProtectedAdminIndexRoute
}

const ProtectedAdminRouteChildren: ProtectedAdminRouteChildren = {
  ProtectedAdminCategoriesRoute: ProtectedAdminCategoriesRoute,
  ProtectedAdminFeedbackRoute: ProtectedAdminFeedbackRoute,
  ProtectedAdminNotificationsRoute: ProtectedAdminNotificationsRoute,
  ProtectedAdminOsceRoute: ProtectedAdminOsceRoute,
  ProtectedAdminPlansRoute: ProtectedAdminPlansRoute,
  ProtectedAdminQuestionsRoute: ProtectedAdminQuestionsRoute,
  ProtectedAdminSupportRoute: ProtectedAdminSupportRoute,
  ProtectedAdminUsersRoute: ProtectedAdminUsersRoute,
  ProtectedAdminIndexRoute: ProtectedAdminIndexRoute,
}

const ProtectedAdminRouteWithChildren = ProtectedAdminRoute._addFileChildren(
  ProtectedAdminRouteChildren,
)

interface ProtectedDashboardRouteChildren {
  ProtectedDashboardBookmarksRoute: typeof ProtectedDashboardBookmarksRoute
  ProtectedDashboardNotesRoute: typeof ProtectedDashboardNotesRoute
  ProtectedDashboardNotificationsRoute: typeof ProtectedDashboardNotificationsRoute
  ProtectedDashboardOsceRoute: typeof ProtectedDashboardOsceRoute
  ProtectedDashboardPracticeRoute: typeof ProtectedDashboardPracticeRoute
  ProtectedDashboardSettingsRoute: typeof ProtectedDashboardSettingsRoute
  ProtectedDashboardSharingRoute: typeof ProtectedDashboardSharingRoute
  ProtectedDashboardSupportRoute: typeof ProtectedDashboardSupportRoute
  ProtectedDashboardIndexRoute: typeof ProtectedDashboardIndexRoute
}

const ProtectedDashboardRouteChildren: ProtectedDashboardRouteChildren = {
  ProtectedDashboardBookmarksRoute: ProtectedDashboardBookmarksRoute,
  ProtectedDashboardNotesRoute: ProtectedDashboardNotesRoute,
  ProtectedDashboardNotificationsRoute: ProtectedDashboardNotificationsRoute,
  ProtectedDashboardOsceRoute: ProtectedDashboardOsceRoute,
  ProtectedDashboardPracticeRoute: ProtectedDashboardPracticeRoute,
  ProtectedDashboardSettingsRoute: ProtectedDashboardSettingsRoute,
  ProtectedDashboardSharingRoute: ProtectedDashboardSharingRoute,
  ProtectedDashboardSupportRoute: ProtectedDashboardSupportRoute,
  ProtectedDashboardIndexRoute: ProtectedDashboardIndexRoute,
}

const ProtectedDashboardRouteWithChildren =
  ProtectedDashboardRoute._addFileChildren(ProtectedDashboardRouteChildren)

interface ProtectedRouteChildren {
  ProtectedAdminRoute: typeof ProtectedAdminRouteWithChildren
  ProtectedAdminSetupRoute: typeof ProtectedAdminSetupRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRouteWithChildren
  ProtectedExampleProtectedRouteRoute: typeof ProtectedExampleProtectedRouteRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedAdminRoute: ProtectedAdminRouteWithChildren,
  ProtectedAdminSetupRoute: ProtectedAdminSetupRoute,
  ProtectedDashboardRoute: ProtectedDashboardRouteWithChildren,
  ProtectedExampleProtectedRouteRoute: ProtectedExampleProtectedRouteRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface PublicRouteChildren {
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  ProtectedRoute: ProtectedRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  ApiHelloRoute: ApiHelloRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
